mongodb:
  uri: "mongodb+srv://<username>:<password>@crop0.ewrndcp.mongodb.net/?retryWrites=true&w=majority&appName=crop0"
  database: "myDatabase"
  collection: "myCollection"

model:
  path: "models/xgboost_model.pkl"
